import type {
  DemoGuideCatalogItem,
  DemoLocalizedLabel,
} from "./types";

const VERIFIED_AT = "2026-08-01";

function localized(
  en: string,
  it: string,
  de: string,
  ru: string,
): DemoLocalizedLabel {
  return { en, it, de, ru };
}

function mapsSearch(query: string): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}

function bookingNote(): DemoLocalizedLabel {
  return localized(
    "We can pass your request to the venue. Availability, access and any final arrangements are confirmed only by its team.",
    "Possiamo inoltrare la richiesta alla struttura. Disponibilità, accesso e accordi finali vengono confermati esclusivamente dal suo staff.",
    "Wir können Ihre Anfrage an den Betrieb weiterleiten. Verfügbarkeit, Zugang und alle endgültigen Absprachen bestätigt ausschließlich das jeweilige Team.",
    "Мы можем передать запрос заведению. Наличие мест, способ доступа и окончательные условия подтверждает только его команда.",
  );
}

export function createGuideSeedCatalog(
  timestamp: string,
): DemoGuideCatalogItem[] {
  const shared = {
    kind: "guide" as const,
    active: true,
    verifiedAt: VERIFIED_AT,
    createdAt: timestamp,
    updatedAt: timestamp,
  };

  return [
    {
      id: "guide-le-tre-sorelle",
      slug: "le-tre-sorelle",
      category: "dining",
      sortOrder: 10,
      labels: localized(
        "Le Tre Sorelle",
        "Le Tre Sorelle",
        "Le Tre Sorelle",
        "Le Tre Sorelle",
      ),
      description: localized(
        "A family osteria beside Spiaggia Grande, serving dishes connected to Positano and Campanian cooking. Its seafront position suits a relaxed meal near the beach. Contact the restaurant for the current menu, dietary needs and accessibility.",
        "Un’osteria di famiglia accanto a Spiaggia Grande, con una cucina legata a Positano e alla tradizione campana. La posizione sul mare invita a una sosta distesa. Per menu, esigenze alimentari e accessibilità conviene contattare direttamente il ristorante.",
        "Eine familiengeführte Osteria an der Spiaggia Grande mit einer Küche, die Positano und Kampanien verbunden ist. Die Lage am Meer eignet sich für eine entspannte Pause. Aktuelle Karte, Ernährungswünsche und Zugänglichkeit bitte direkt erfragen.",
        "Семейная остерия рядом со Спьяджа-Гранде с кухней, связанной с Позитано и традициями Кампании. Расположение у моря подходит для спокойного обеда. Актуальное меню, особенности питания и доступность лучше уточнить напрямую.",
      ),
      bookingNote: bookingNote(),
      address: "Via del Brigantino 27/29, 84017 Positano SA",
      phone: "+39 089 875452",
      websiteUrl: "https://www.letresorellepositano.it/en/",
      mapsUrl: mapsSearch("Le Tre Sorelle Positano"),
      requestable: true,
      ...shared,
    },
    {
      id: "guide-da-vincenzo",
      slug: "da-vincenzo",
      category: "dining",
      sortOrder: 20,
      labels: localized(
        "Da Vincenzo",
        "Da Vincenzo",
        "Da Vincenzo",
        "Da Vincenzo",
      ),
      description: localized(
        "A long-standing family restaurant on Viale Pasitea, with cooking rooted in Positano and Campania. The setting is traditional and welcoming. Ask the restaurant about the day’s menu, dietary requirements and the easiest route from your room.",
        "Un ristorante di famiglia da lungo tempo in Viale Pasitea, con una cucina radicata a Positano e in Campania. L’ambiente è tradizionale e accogliente. Chiedete direttamente menu del giorno, esigenze alimentari e percorso più semplice dalla camera.",
        "Ein traditionsreiches Familienrestaurant an der Viale Pasitea mit einer in Positano und Kampanien verwurzelten Küche. Das Ambiente ist klassisch und einladend. Tageskarte, Ernährungswünsche und den einfachsten Weg von Ihrem Zimmer bitte direkt erfragen.",
        "Давний семейный ресторан на Виале-Пазитеа с кухней, основанной на традициях Позитано и Кампании. Обстановка классическая и гостеприимная. Меню дня, особенности питания и самый удобный путь от номера лучше уточнить напрямую.",
      ),
      bookingNote: bookingNote(),
      address: "Viale Pasitea 172, 84017 Positano SA",
      phone: "+39 089 875128",
      websiteUrl: "https://www.davincenzo1958.com/",
      mapsUrl: mapsSearch("Da Vincenzo Positano"),
      requestable: true,
      ...shared,
    },
    {
      id: "guide-il-ritrovo",
      slug: "il-ritrovo",
      category: "dining",
      sortOrder: 30,
      labels: localized(
        "Il Ritrovo",
        "Il Ritrovo",
        "Il Ritrovo",
        "Il Ritrovo",
      ),
      description: localized(
        "A family-run restaurant in the hillside village of Montepertuso, centred on regional ingredients and generous hospitality. The journey is part of the evening, so agree transport and return arrangements with the restaurant before leaving Positano.",
        "Un ristorante familiare nel borgo collinare di Montepertuso, attento agli ingredienti regionali e a un’ospitalità generosa. Il tragitto fa parte della serata: prima di partire da Positano concordate con il ristorante trasporto e rientro.",
        "Ein Familienrestaurant im Bergdorf Montepertuso, geprägt von regionalen Zutaten und herzlicher Gastlichkeit. Auch die Anfahrt gehört zum Abend: Klären Sie vor der Abfahrt aus Positano den Hin- und Rückweg direkt mit dem Restaurant.",
        "Семейный ресторан в горной деревне Монтепертузо, где ценят местные продукты и радушный приём. Дорога становится частью вечера, поэтому до выезда из Позитано согласуйте с рестораном транспорт туда и обратно.",
      ),
      bookingNote: bookingNote(),
      address: "Piazza Cappella 3, 84017 Positano SA",
      phone: "+39 089 875453",
      websiteUrl: "https://www.ilritrovo.com/en/",
      mapsUrl: mapsSearch("Il Ritrovo Montepertuso Positano"),
      requestable: true,
      ...shared,
    },
    {
      id: "guide-la-tagliata",
      slug: "la-tagliata",
      category: "dining",
      sortOrder: 40,
      labels: localized(
        "La Tagliata",
        "La Tagliata",
        "La Tagliata",
        "La Tagliata",
      ),
      description: localized(
        "A family farm restaurant above Positano, where the table follows the produce and cooking of the surrounding hills. It is outside the pedestrian centre; confirm the meeting point, transport and any dietary requirements directly before the visit.",
        "Un ristorante agricolo di famiglia sopra Positano, dove la tavola segue i prodotti e la cucina delle colline circostanti. È fuori dal centro pedonale: prima della visita confermate direttamente punto d’incontro, trasporto ed eventuali esigenze alimentari.",
        "Ein familiengeführtes Hofrestaurant oberhalb von Positano, dessen Küche den Erzeugnissen der umliegenden Hügel folgt. Es liegt außerhalb des Fußgängerzentrums; Treffpunkt, Transport und besondere Ernährungswünsche sollten vor dem Besuch direkt bestätigt werden.",
        "Семейный фермерский ресторан над Позитано, где кухня следует продуктам окрестных холмов. Он находится вне пешеходного центра: перед визитом напрямую подтвердите место встречи, транспорт и возможные особенности питания.",
      ),
      bookingNote: bookingNote(),
      address: "Via Tagliata 32B, 84017 Positano SA",
      phone: "+39 089 875872",
      websiteUrl: "https://www.latagliata.com/",
      mapsUrl: mapsSearch("La Tagliata Positano"),
      requestable: true,
      ...shared,
    },
    {
      id: "guide-casa-e-bottega",
      slug: "casa-e-bottega",
      category: "dining",
      sortOrder: 50,
      labels: localized(
        "Casa e Bottega",
        "Casa e Bottega",
        "Casa e Bottega",
        "Casa e Bottega",
      ),
      description: localized(
        "A daytime café and design shop pairing fresh Mediterranean-inspired dishes with ceramics, textiles and objects for the home. It is a calm stop along Via Pasitea. Check the official site for current service and walk-in arrangements.",
        "Un caffè diurno e bottega di design che unisce piatti freschi d’ispirazione mediterranea a ceramiche, tessili e oggetti per la casa. È una sosta tranquilla lungo Via Pasitea. Consultate il sito ufficiale per il servizio aggiornato.",
        "Ein Tagescafé mit Designladen, das frische mediterran inspirierte Gerichte mit Keramik, Textilien und Wohnobjekten verbindet. Eine ruhige Station an der Via Pasitea. Aktuelle Hinweise zu Service und Besuch finden Sie auf der offiziellen Website.",
        "Дневное кафе и магазин дизайна, где свежие блюда в средиземноморском духе соседствуют с керамикой, текстилем и предметами для дома. Спокойная остановка на Виа-Пазитеа. Актуальный формат обслуживания смотрите на официальном сайте.",
      ),
      address: "Via Pasitea 100, 84017 Positano SA",
      phone: "+39 089 875225",
      websiteUrl:
        "https://www.casaebottegapositano.it/pages/casa-e-bottega",
      mapsUrl: mapsSearch("Casa e Bottega Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-collina-positano-bakery",
      slug: "collina-positano-bakery",
      category: "dining",
      sortOrder: 60,
      labels: localized(
        "Collina Positano Bakery",
        "Collina Positano Bakery",
        "Collina Positano Bakery",
        "Collina Positano Bakery",
      ),
      description: localized(
        "A family bakery near Piazza dei Mulini, offering pastry, gelato, coffee and savoury baking in an informal setting. It works well for a simple breakfast or pause while crossing the centre. Check seasonal opening directly.",
        "Una pasticceria di famiglia vicino a Piazza dei Mulini, con dolci, gelato, caffè e prodotti salati in un ambiente informale. È adatta a una colazione semplice o a una pausa attraversando il centro. Verificate l’apertura stagionale.",
        "Eine Familienbäckerei nahe der Piazza dei Mulini mit Gebäck, Eis, Kaffee und herzhaften Backwaren in ungezwungener Atmosphäre. Gut für ein einfaches Frühstück oder eine Pause im Zentrum. Die saisonale Öffnung bitte direkt prüfen.",
        "Семейная пекарня рядом с Пьяцца-деи-Мулини: выпечка, мороженое, кофе и несладкие изделия в непринуждённой обстановке. Удобна для простого завтрака или паузы в центре. Сезонное открытие лучше проверить напрямую.",
      ),
      address: "Via Cristoforo Colombo 1/3, 84017 Positano SA",
      phone: "+39 089 875433",
      websiteUrl: "https://www.collinabakery.com/",
      mapsUrl: mapsSearch("Collina Positano Bakery"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-la-zagara",
      slug: "la-zagara",
      category: "dining",
      sortOrder: 70,
      labels: localized(
        "La Zagara",
        "La Zagara",
        "La Zagara",
        "La Zagara",
      ),
      description: localized(
        "A garden café and pastry shop among citrus trees in the pedestrian centre. It suits a coffee, a house-made sweet or an unhurried pause between the upper road and the beach. Consult the official site before visiting.",
        "Un caffè e pasticceria in giardino, tra gli agrumi del centro pedonale. È adatto a un caffè, un dolce della casa o una pausa senza fretta tra la strada alta e la spiaggia. Consultate il sito prima della visita.",
        "Ein Gartencafé mit Konditorei unter Zitrusbäumen im Fußgängerzentrum. Es eignet sich für Kaffee, hausgemachtes Gebäck oder eine ruhige Pause zwischen oberer Straße und Strand. Hinweise vor dem Besuch stehen auf der offiziellen Website.",
        "Садовое кафе и кондитерская среди цитрусовых деревьев в пешеходном центре. Подходит для кофе, домашнего десерта или неторопливой паузы между верхней дорогой и пляжем. Перед визитом загляните на официальный сайт.",
      ),
      address: "Via dei Mulini 10, 84017 Positano SA",
      phone: "+39 089 875964",
      websiteUrl: "https://www.lazagara.com/",
      mapsUrl: mapsSearch("La Zagara Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-francos-bar",
      slug: "francos-bar",
      category: "after-dark",
      sortOrder: 110,
      labels: localized(
        "Franco’s Bar",
        "Franco’s Bar",
        "Franco’s Bar",
        "Franco’s Bar",
      ),
      description: localized(
        "Le Sirenuse’s open-air cocktail bar, with a terrace facing the coast and a carefully designed setting. Service is seasonal and weather-dependent, and seating is generally informal. Check the official site before walking over.",
        "Il cocktail bar all’aperto de Le Sirenuse, con terrazza rivolta verso la costa e un ambiente curato. Il servizio è stagionale e dipende dal meteo, con accesso generalmente informale. Controllate il sito ufficiale prima di raggiungerlo.",
        "Die offene Cocktailbar des Le Sirenuse mit einer zur Küste gerichteten, sorgfältig gestalteten Terrasse. Der Betrieb ist saison- und wetterabhängig, die Platzvergabe meist ungezwungen. Prüfen Sie vor dem Weg dorthin die offizielle Website.",
        "Открытый коктейль-бар Le Sirenuse с террасой, обращённой к побережью, и тщательно оформленной обстановкой. Работа зависит от сезона и погоды, посадка обычно свободная. Перед прогулкой проверьте официальный сайт.",
      ),
      address: "Via Cristoforo Colombo 30, 84017 Positano SA",
      phone: "+39 089 812189",
      websiteUrl: "https://francosbar.com/en",
      mapsUrl: mapsSearch("Franco's Bar Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-baccos",
      slug: "baccos",
      category: "after-dark",
      sortOrder: 120,
      labels: localized("Bacco’s", "Bacco’s", "Bacco’s", "Bacco’s"),
      description: localized(
        "The open-air lounge terrace of Buca di Bacco, overlooking Spiaggia Grande. It is intended for an aperitif, a cocktail or a light meal close to the beach. Confirm current access and service with the venue.",
        "La terrazza lounge all’aperto della Buca di Bacco, affacciata su Spiaggia Grande. È pensata per un aperitivo, un cocktail o un pasto leggero vicino alla spiaggia. Confermate direttamente accesso e servizio del momento.",
        "Die offene Lounge-Terrasse der Buca di Bacco mit Blick auf die Spiaggia Grande. Sie eignet sich für Aperitif, Cocktail oder eine leichte Mahlzeit nahe dem Strand. Aktuellen Zugang und Service bitte direkt bestätigen.",
        "Открытая лаунж-терраса Buca di Bacco с видом на Спьяджа-Гранде. Подходит для аперитива, коктейля или лёгкой еды рядом с пляжем. Текущий режим доступа и обслуживания лучше подтвердить напрямую.",
      ),
      address: "Via Rampa Teglia 4, 84017 Positano SA",
      phone: "+39 089 875699",
      websiteUrl: "https://www.ristorantebucadibacco.it/en/baccos/",
      mapsUrl: mapsSearch("Bacco's Buca di Bacco Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-music-on-the-rocks",
      slug: "music-on-the-rocks",
      category: "after-dark",
      sortOrder: 130,
      labels: localized(
        "Music on the Rocks",
        "Music on the Rocks",
        "Music on the Rocks",
        "Music on the Rocks",
      ),
      description: localized(
        "A long-established disco club inside the rock beside Spiaggia Grande. Events, entry rules and seasonal programme can change, so consult the official channel on the day. Plan a safe late-night return before going out.",
        "Una discoteca storica ricavata nella roccia accanto a Spiaggia Grande. Eventi, regole d’ingresso e programma stagionale possono cambiare: consultate il canale ufficiale in giornata e organizzate prima un rientro notturno sicuro.",
        "Ein traditionsreicher Club im Felsen an der Spiaggia Grande. Veranstaltungen, Einlassregeln und Saisonprogramm können wechseln; prüfen Sie deshalb am selben Tag den offiziellen Kanal. Organisieren Sie vor dem Ausgehen einen sicheren nächtlichen Rückweg.",
        "Давний ночной клуб в скале рядом со Спьяджа-Гранде. События, правила входа и сезонная программа меняются, поэтому проверяйте официальный канал в тот же день. Заранее продумайте безопасное возвращение ночью.",
      ),
      address: "Località Grotte dell’Incanto 51, 84017 Positano SA",
      phone: "+39 089 875874",
      websiteUrl: "https://registration.musicontherocks.it/",
      mapsUrl: mapsSearch("Music on the Rocks Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-da-adolfo",
      slug: "da-adolfo",
      category: "sea",
      sortOrder: 210,
      labels: localized(
        "Da Adolfo",
        "Da Adolfo",
        "Da Adolfo",
        "Da Adolfo",
      ),
      description: localized(
        "A family restaurant and beach service at Laurito, reached by sea when the boat operates or by a steep land route. Access depends on sea conditions. The official site asks guests to handle confirmed reservations by telephone.",
        "Un ristorante di famiglia con servizio spiaggia a Laurito, raggiungibile via mare quando la barca è operativa oppure da un ripido percorso a terra. L’accesso dipende dal mare; il sito ufficiale richiede conferme telefoniche.",
        "Ein Familienrestaurant mit Strandservice in Laurito, bei Betrieb per Boot oder über einen steilen Landweg erreichbar. Der Zugang hängt vom Seegang ab. Laut offizieller Website werden bestätigte Reservierungen telefonisch geregelt.",
        "Семейный ресторан с пляжным сервисом в Лаурито; добраться можно морем, когда ходит лодка, либо по крутому наземному пути. Доступ зависит от моря, а официальный сайт просит подтверждать бронирование по телефону.",
      ),
      bookingNote: bookingNote(),
      address: "Via Laurito 40, 84017 Positano SA",
      phone: "+39 089 875022",
      websiteUrl: "https://www.daadolfo.com/",
      mapsUrl: mapsSearch("Da Adolfo Laurito Positano"),
      requestable: true,
      ...shared,
    },
    {
      id: "guide-arienzo-beach-club",
      slug: "arienzo-beach-club",
      category: "sea",
      sortOrder: 220,
      labels: localized(
        "Arienzo Beach Club",
        "Arienzo Beach Club",
        "Arienzo Beach Club",
        "Arienzo Beach Club",
      ),
      description: localized(
        "A managed beach club in the Arienzo cove, accessible by sea when its shuttle operates or by the long stairway from the coastal road. Boat service can change with weather and operations; confirm instructions before departure.",
        "Uno stabilimento nella cala di Arienzo, raggiungibile via mare quando opera la navetta oppure dalla lunga scalinata sulla strada costiera. Il servizio barca può variare per meteo e operatività: confermate le istruzioni prima di partire.",
        "Ein bewirtschafteter Strandclub in der Bucht von Arienzo, bei Betrieb per Shuttleboot oder über die lange Treppe von der Küstenstraße erreichbar. Der Bootsservice ist wetter- und betriebsabhängig; Hinweise vor der Abfahrt bestätigen.",
        "Оборудованный пляжный клуб в бухте Арьенцо: доступен морским шаттлом, когда тот работает, либо по длинной лестнице от прибрежной дороги. Лодочное сообщение зависит от погоды и работы сервиса; заранее подтвердите инструкции.",
      ),
      bookingNote: bookingNote(),
      address: "Spiaggia di Arienzo, Via Arienzo 16, 84017 Positano SA",
      phone: "+39 338 8778082",
      websiteUrl: "https://www.arienzobeachclub.com/",
      mapsUrl: mapsSearch("Arienzo Beach Club Positano"),
      requestable: true,
      ...shared,
    },
    {
      id: "guide-pupetto-beach-club",
      slug: "pupetto-beach-club",
      category: "sea",
      sortOrder: 230,
      labels: localized(
        "Pupetto Beach Club",
        "Pupetto Beach Club",
        "Pupetto Beach Club",
        "Pupetto Beach Club",
      ),
      description: localized(
        "A beach club and seaside restaurant on Fornillo, reached on foot along the coastal path from Spiaggia Grande. The route includes uneven sections and steps. Check the official booking channel and access details before setting out.",
        "Uno stabilimento con ristorante sul mare a Fornillo, raggiungibile a piedi dal sentiero costiero che parte da Spiaggia Grande. Il percorso comprende tratti irregolari e gradini. Controllate prenotazione e accesso sul canale ufficiale.",
        "Ein Strandclub mit Restaurant am Fornillo-Strand, zu Fuß über den Küstenweg von der Spiaggia Grande erreichbar. Der Weg umfasst unebene Abschnitte und Stufen. Buchung und Zugang bitte vorab über den offiziellen Kanal prüfen.",
        "Пляжный клуб и ресторан у моря на Форнилло, куда идут пешком по прибрежной дорожке от Спьяджа-Гранде. На пути есть неровные участки и ступени. Заранее проверьте бронирование и доступ на официальном канале.",
      ),
      bookingNote: bookingNote(),
      address: "Spiaggia di Fornillo, 84017 Positano SA",
      phone: "+39 089 9357455",
      websiteUrl: "https://www.pupettobeachclub.it/en/home",
      mapsUrl: mapsSearch("Pupetto Beach Club Positano"),
      requestable: true,
      ...shared,
    },
    {
      id: "guide-marina-grande",
      slug: "marina-grande",
      category: "sea",
      sortOrder: 240,
      labels: localized(
        "Marina Grande",
        "Marina Grande",
        "Marina Grande",
        "Марина-Гранде",
      ),
      description: localized(
        "Positano’s main beach and ferry landing, reached through the pedestrian centre. It combines public access, managed beach areas and the working pier, so it is often lively. Keep the boarding zone clear and check sea departures the same day.",
        "La spiaggia principale e il molo di Positano, raggiungibili attraversando il centro pedonale. Riunisce accesso pubblico, aree gestite e imbarco, quindi è spesso vivace. Lasciate libero il molo e controllate le partenze in giornata.",
        "Positanos Hauptstrand und Fähranleger, erreichbar durch das Fußgängerzentrum. Öffentlicher Zugang, bewirtschaftete Strandbereiche und der aktive Anleger liegen nebeneinander, daher ist es oft belebt. Halten Sie den Einstiegsbereich frei und prüfen Sie Abfahrten tagesaktuell.",
        "Главный пляж и паромный причал Позитано, к которым ведёт путь через пешеходный центр. Здесь соседствуют общественная зона, оборудованные участки и рабочий причал, поэтому бывает оживлённо. Не загромождайте посадку и проверяйте рейсы в тот же день.",
      ),
      address: "Via del Brigantino, 84017 Positano SA",
      websiteUrl:
        "https://comune.positano.sa.it/vivere-il-comune/luogo/bellezza-naturale/spiaggia-di-marina-grande",
      mapsUrl: mapsSearch("Spiaggia Grande Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-fornillo-beach",
      slug: "fornillo-beach",
      category: "sea",
      sortOrder: 250,
      labels: localized(
        "Fornillo Beach",
        "Spiaggia di Fornillo",
        "Fornillo-Strand",
        "Пляж Форнилло",
      ),
      description: localized(
        "A cove west of the main beach, connected by a scenic pedestrian path and stairs. Public stretches sit alongside managed beach services. Wear suitable shoes, allow energy for the return climb and confirm seasonal facilities locally.",
        "Una cala a ovest della spiaggia principale, collegata da un percorso pedonale panoramico e da scale. Tratti liberi convivono con stabilimenti. Indossate scarpe adatte, conservate energie per il rientro in salita e verificate i servizi stagionali.",
        "Eine Bucht westlich des Hauptstrands, über einen aussichtsreichen Fußweg und Treppen erreichbar. Freie Abschnitte liegen neben bewirtschafteten Bereichen. Tragen Sie geeignetes Schuhwerk, planen Sie Kraft für den Rückweg bergauf ein und prüfen Sie saisonale Angebote vor Ort.",
        "Бухта к западу от главного пляжа, связанная с ним живописной пешеходной дорожкой и лестницами. Общественные участки соседствуют с оборудованными. Нужна удобная обувь; оставьте силы на подъём обратно и уточните сезонные услуги на месте.",
      ),
      address: "Via Fornillo 41, 84017 Positano SA",
      websiteUrl:
        "https://comune.positano.sa.it/vivere-il-comune/luogo/bellezza-naturale/spiaggia-di-fornillo",
      mapsUrl: mapsSearch("Spiaggia di Fornillo Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-arienzo-laurito-public-beaches",
      slug: "arienzo-laurito-public-beaches",
      category: "sea",
      sortOrder: 260,
      labels: localized(
        "Arienzo and Laurito public beaches",
        "Spiagge libere di Arienzo e Laurito",
        "Öffentliche Strandbereiche Arienzo und Laurito",
        "Общественные пляжи Арьенцо и Лаурито",
      ),
      description: localized(
        "The public portions of these small coves are separate from private beach services. Land access involves long, steep stairways, while sea access varies by operator and conditions. They are not a simple choice for reduced mobility.",
        "Le porzioni libere di queste piccole cale sono separate dagli stabilimenti privati. L’accesso da terra richiede scalinate lunghe e ripide; quello via mare varia secondo operatori e condizioni. Non sono una scelta semplice per mobilità ridotta.",
        "Die öffentlichen Abschnitte dieser kleinen Buchten sind von privaten Strandbetrieben getrennt. Der Landzugang führt über lange, steile Treppen; der Seeweg hängt von Anbietern und Bedingungen ab. Für eingeschränkte Mobilität sind sie keine einfache Wahl.",
        "Общественные части этих небольших бухт отделены от частных пляжных сервисов. Наземный путь проходит по длинным крутым лестницам, а доступ морем зависит от оператора и условий. Для ограниченной подвижности это непростой вариант.",
      ),
      address: "Via Arienzo 47 / Via Laurito 24, 84017 Positano SA",
      websiteUrl: "https://comune.positano.sa.it/argomenti/turismo",
      mapsUrl: mapsSearch("Spiaggia di Arienzo Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-mar-positano",
      slug: "mar-positano",
      category: "see",
      sortOrder: 310,
      labels: localized(
        "MAR Positano",
        "MAR Positano",
        "MAR Positano",
        "MAR Positano",
      ),
      description: localized(
        "The Roman Archaeological Museum reveals the villa buried beneath central Positano, with preserved wall painting and later medieval spaces. Visits follow the museum’s access arrangements. Check the official ticket office for current admission and language options.",
        "Il Museo Archeologico Romano racconta la villa sepolta sotto il centro di Positano, con pitture conservate e successivi ambienti medievali. La visita segue le modalità del museo. Verificate sul sito ufficiale accessi e lingue disponibili.",
        "Das Römische Archäologische Museum erschließt die unter Positanos Zentrum verschüttete Villa mit erhaltenen Wandmalereien und späteren mittelalterlichen Räumen. Besuche folgen den Zugangsregeln des Museums. Aktuelle Einlass- und Sprachoptionen bitte beim offiziellen Ticketbüro prüfen.",
        "Римский археологический музей показывает виллу, погребённую под центром Позитано, с сохранившимися росписями и более поздними средневековыми помещениями. Посещение проходит по правилам музея; актуальный доступ и языки уточняйте в официальной кассе.",
      ),
      address: "Piazza Flavio Gioia 7, 84017 Positano SA",
      phone: "+39 331 2085821",
      websiteUrl: "https://marpositano.it/web/en/",
      mapsUrl: mapsSearch("MAR Museo Archeologico Romano Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-santa-maria-assunta",
      slug: "santa-maria-assunta",
      category: "see",
      sortOrder: 320,
      labels: localized(
        "Church of Santa Maria Assunta",
        "Chiesa di Santa Maria Assunta",
        "Kirche Santa Maria Assunta",
        "Церковь Санта-Мария-Ассунта",
      ),
      description: localized(
        "Positano’s central parish church, recognised by its majolica dome and connected to the town’s religious history. It remains an active place of worship: enter quietly, dress respectfully and avoid sightseeing during services or private ceremonies.",
        "La chiesa parrocchiale nel centro di Positano, riconoscibile dalla cupola maiolicata e legata alla storia religiosa del paese. È un luogo di culto attivo: entrate in silenzio, vestite con rispetto ed evitate visite durante funzioni o cerimonie.",
        "Positanos zentrale Pfarrkirche ist an ihrer Majolikakuppel erkennbar und eng mit der religiösen Geschichte des Ortes verbunden. Sie bleibt ein aktiver Andachtsort: leise eintreten, angemessen kleiden und Besichtigungen während Gottesdiensten oder Feiern vermeiden.",
        "Главная приходская церковь Позитано узнаваема по майоликовому куполу и связана с религиозной историей города. Это действующий храм: входите тихо, одевайтесь уважительно и не осматривайте церковь во время служб или частных церемоний.",
      ),
      address: "Piazza Flavio Gioia, 84017 Positano SA",
      websiteUrl:
        "https://comune.positano.sa.it/vivere-il-comune/luogo/edificio-di-culto/chiesa-di-santa-maria-assunta",
      mapsUrl: mapsSearch("Chiesa di Santa Maria Assunta Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-path-of-gods-nocelle",
      slug: "path-of-gods-nocelle",
      category: "see",
      sortOrder: 330,
      labels: localized(
        "Path of the Gods and Nocelle",
        "Sentiero degli Dei e Nocelle",
        "Weg der Götter und Nocelle",
        "Тропа богов и Ночелле",
      ),
      description: localized(
        "Nocelle is Positano’s high village and a gateway to the exposed Path of the Gods. The historic stair route to town has about 1,700 steps. Take water, proper footwear and local advice; avoid heat, rain and strong wind.",
        "Nocelle è il borgo alto di Positano e una porta sul Sentiero degli Dei, esposto e panoramico. La scala storica verso il paese conta circa 1.700 gradini. Portate acqua, scarpe adatte e informazioni locali; evitate caldo, pioggia e vento forte.",
        "Nocelle ist Positanos hoch gelegenes Dorf und Zugang zum ausgesetzten Weg der Götter. Die historische Treppe zum Ort zählt etwa 1.700 Stufen. Wasser, festes Schuhwerk und lokale Hinweise sind wichtig; Hitze, Regen und starken Wind meiden.",
        "Ночелле — высокогорная деревня Позитано и выход к открытой Тропе богов. На исторической лестнице к городу около 1700 ступеней. Нужны вода, подходящая обувь и местная информация; избегайте жары, дождя и сильного ветра.",
      ),
      address: "Nocelle, 84017 Positano SA",
      websiteUrl:
        "https://comune.positano.sa.it/vivere-il-comune/luogo/bellezza-naturale/frazione-di-nocelle",
      mapsUrl: mapsSearch("Nocelle Positano Sentiero degli Dei"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-montepertuso",
      slug: "montepertuso",
      category: "see",
      sortOrder: 340,
      labels: localized(
        "Montepertuso",
        "Montepertuso",
        "Montepertuso",
        "Монтепертузо",
      ),
      description: localized(
        "A residential hillside village above Positano, known for the natural opening in the mountain and the Church of Santa Maria delle Grazie. Visit gently and keep noise low. Check local transport before leaving, especially for the return.",
        "Un borgo residenziale sulle alture di Positano, noto per l’apertura naturale nella montagna e la Chiesa di Santa Maria delle Grazie. Visitatelo con discrezione e poco rumore. Controllate il trasporto locale, soprattutto per il rientro.",
        "Ein bewohntes Bergdorf oberhalb Positanos, bekannt für die natürliche Öffnung im Fels und die Kirche Santa Maria delle Grazie. Nehmen Sie Rücksicht und vermeiden Sie Lärm. Prüfen Sie den Nahverkehr, besonders für die Rückfahrt.",
        "Жилая горная деревня над Позитано, известная естественным отверстием в скале и церковью Санта-Мария-делле-Грацие. Посещайте её бережно и без шума. Заранее проверьте местный транспорт, особенно обратный путь.",
      ),
      address: "Via Montepertuso 130, 84017 Positano SA",
      websiteUrl:
        "https://comune.positano.sa.it/vivere-il-comune/luogo/edificio-di-culto/chiesa-s-maria-delle-grazie",
      mapsUrl: mapsSearch("Montepertuso Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-tourist-office",
      slug: "positano-tourist-office",
      category: "essentials",
      sortOrder: 410,
      labels: localized(
        "Positano Tourist Office",
        "Ufficio del Turismo di Positano",
        "Tourismusbüro Positano",
        "Туристический офис Позитано",
      ),
      description: localized(
        "The municipal information point for local maps, cultural visits, events and practical updates. It is the most reliable first stop for current advice on paths, public transport and town services. Opening arrangements can be checked directly.",
        "Il punto informativo comunale per mappe, visite culturali, eventi e aggiornamenti pratici. È il primo riferimento affidabile per indicazioni attuali su sentieri, trasporto pubblico e servizi del paese. Verificate direttamente l’apertura.",
        "Die kommunale Anlaufstelle für Ortspläne, Kulturangebote, Veranstaltungen und praktische Hinweise. Sie ist die verlässlichste erste Adresse für aktuelle Informationen zu Wegen, öffentlichem Verkehr und Gemeindediensten. Öffnung bitte direkt prüfen.",
        "Муниципальный информационный пункт с картами, сведениями о культурных посещениях, событиях и практических изменениях. Это первый надёжный источник актуальной информации о тропах, общественном транспорте и городских службах. Режим работы уточняйте напрямую.",
      ),
      address: "Viale Regina Giovanna 13, 84017 Positano SA",
      phone: "+39 335 7328002",
      websiteUrl:
        "https://comune.positano.sa.it/vivere-il-comune/luogo/palazzo/ufficio-del-turismo",
      mapsUrl: mapsSearch("Ufficio del Turismo Positano"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-sita-sud",
      slug: "sita-sud",
      category: "getting-around",
      sortOrder: 420,
      labels: localized(
        "SITA Sud buses",
        "Autobus SITA Sud",
        "Busse von SITA Sud",
        "Автобусы SITA Sud",
      ),
      description: localized(
        "Official bus operator for Amalfi Coast routes and current local links around Positano. Use only marked stops and valid tickets. Roads and services can change quickly, so consult the live timetable and service notices on the day.",
        "Il gestore ufficiale degli autobus della Costiera e degli attuali collegamenti locali intorno a Positano. Usate solo fermate segnalate e titoli validi. Strade e servizi cambiano rapidamente: controllate orari e avvisi in giornata.",
        "Offizieller Busbetreiber für die Amalfiküste und aktuelle Nahverbindungen rund um Positano. Nutzen Sie nur gekennzeichnete Haltestellen und gültige Fahrscheine. Straßenlage und Verkehr ändern sich rasch; Fahrplan und Meldungen am Reisetag prüfen.",
        "Официальный автобусный оператор побережья Амальфи и текущих местных маршрутов вокруг Позитано. Пользуйтесь только обозначенными остановками и действительными билетами. Дорожная ситуация быстро меняется, поэтому проверяйте расписание и уведомления в день поездки.",
      ),
      address: "Positano · fermate ufficiali",
      websiteUrl: "https://sitasudtrasporti.it/campania/orari/",
      mapsUrl: mapsSearch("SITA bus stop Positano Sponda"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-travelmar",
      slug: "travelmar",
      category: "getting-around",
      sortOrder: 430,
      labels: localized(
        "Travelmar ferries",
        "Traghetti Travelmar",
        "Travelmar-Fähren",
        "Паромы Travelmar",
      ),
      description: localized(
        "Passenger ferries connecting Positano with other Amalfi Coast ports from the Marina Grande pier. Routes depend on season, sea and weather. Check departures the same day, allow time at the pier and keep a land alternative.",
        "Traghetti passeggeri dal molo di Marina Grande verso altri porti della Costiera Amalfitana. Le rotte dipendono da stagione, mare e meteo. Controllate le partenze in giornata, arrivate con anticipo e mantenete un’alternativa via terra.",
        "Passagierfähren verbinden Positano vom Anleger Marina Grande mit weiteren Häfen der Amalfiküste. Verbindungen hängen von Saison, See und Wetter ab. Abfahrten am selben Tag prüfen, Zeit am Anleger einplanen und eine Landalternative bereithalten.",
        "Пассажирские паромы от причала Марина-Гранде связывают Позитано с другими портами Амальфитанского побережья. Маршруты зависят от сезона, моря и погоды. Проверяйте рейсы в тот же день, приходите заранее и сохраняйте наземную альтернативу.",
      ),
      address: "Molo di Positano, Spiaggia Grande, 84017 Positano SA",
      phone: "+39 089 872950",
      websiteUrl: "https://italo.travelmar.it/en/timetable",
      mapsUrl: mapsSearch("Travelmar Positano ferry terminal"),
      requestable: false,
      ...shared,
    },
    {
      id: "guide-farmacia-positano",
      slug: "farmacia-positano",
      category: "essentials",
      sortOrder: 440,
      labels: localized(
        "Farmacia Positano",
        "Farmacia Positano",
        "Farmacia Positano",
        "Аптека Positano",
      ),
      description: localized(
        "The town pharmacy for medicines and everyday health needs on Viale Pasitea. Call ahead for current opening, prescription questions and duty service. For urgent medical help use the official emergency channels rather than relying on shop availability.",
        "La farmacia del paese per medicinali e necessità sanitarie quotidiane, in Viale Pasitea. Chiamate per apertura aggiornata, ricette e servizio di turno. Per assistenza urgente usate i canali ufficiali d’emergenza, senza affidarvi alla disponibilità del negozio.",
        "Die Ortsapotheke an der Viale Pasitea für Arzneimittel und alltägliche Gesundheitsfragen. Rufen Sie wegen aktueller Öffnung, Rezepten und Notdienst an. Bei dringender medizinischer Hilfe nutzen Sie die offiziellen Notrufwege statt sich auf die Ladenöffnung zu verlassen.",
        "Городская аптека на Виале-Пазитеа для лекарств и повседневных медицинских нужд. Позвоните, чтобы уточнить работу, рецепты и дежурную службу. В срочной ситуации обращайтесь по официальным экстренным каналам, не полагаясь на открытие магазина.",
      ),
      address: "Viale Pasitea 22, 84017 Positano SA",
      phone: "+39 089 875863",
      websiteUrl: "https://www.positanofarmacia.it/",
      mapsUrl: mapsSearch("Farmacia Positano Viale Pasitea 22"),
      requestable: false,
      ...shared,
    },
  ];
}
