import type {
  ConciergeApiErrorCode,
  ConciergeLocale,
  ConciergeVoice,
} from "@/lib/concierge/contract";

interface ConciergeCopy {
  eyebrow: string;
  title: string;
  lead: string;
  languageLabel: string;
  voiceLegend: string;
  voices: Record<ConciergeVoice, string>;
  aiDisclosure: string;
  privacyNote: string;
  chatTitle: string;
  checking: string;
  ready: string;
  unavailable: string;
  newConversation: string;
  confirmNewConversation: string;
  welcome: string;
  assistantName: string;
  guestName: string;
  quickPrompts: string[];
  suggestionsLabel: string;
  inputLabel: string;
  inputPlaceholder: string;
  send: string;
  sending: string;
  listen: string;
  stop: string;
  officialSite: string;
  maps: string;
  request: string;
  errors: Record<ConciergeApiErrorCode, string>;
}

export const conciergeCopy: Record<ConciergeLocale, ConciergeCopy> = {
  en: {
    eyebrow: "A quiet word, whenever you need it",
    title: "Your personal concierge",
    lead:
      "Ask for a table, a swim or an unhurried day. We answer from our selected Positano guide and leave every final choice with you.",
    languageLabel: "Concierge language",
    voiceLegend: "Voice",
    voices: { female: "Female voice", male: "Male voice" },
    aiDisclosure: "The voice you hear is generated by artificial intelligence.",
    privacyNote:
      "When you use the concierge, your question, a short conversation history and the relevant guide entries are sent to OpenAI. If you choose Listen, the response text is sent again to generate the audio. Do not include sensitive or confidential information.",
    chatTitle: "Fenice concierge",
    checking: "Checking availability",
    ready: "Available",
    unavailable: "Temporarily unavailable",
    newConversation: "New conversation",
    confirmNewConversation: "Confirm reset",
    welcome:
      "Welcome. Tell me what kind of moment you have in mind and I’ll help you look through our Positano addresses.",
    assistantName: "Concierge",
    guestName: "You",
    quickPrompts: [
      "A family dinner nearby",
      "A quiet day by the sea",
      "What should we see today?",
      "How can we get around?",
    ],
    suggestionsLabel: "Suggestions",
    inputLabel: "Ask the concierge",
    inputPlaceholder: "For example: where could we have a quiet dinner?",
    send: "Send",
    sending: "Thinking…",
    listen: "Listen",
    stop: "Stop",
    officialSite: "Official site",
    maps: "Maps",
    request: "Ask La Fenice",
    errors: {
      invalid_request: "Please shorten or rephrase your question.",
      invalid_origin: "This request cannot be sent from the current page.",
      not_authenticated: "Sign in again to use the virtual concierge.",
      not_configured: "The virtual concierge has not yet been connected.",
      rate_limited: "A short pause, please. Try again in a moment.",
      content_blocked: "I can’t help with that request. Try a question about your stay.",
      provider_unavailable: "The concierge is resting for a moment. The guide below remains available.",
      invalid_speech_token: "This audio link has expired. Ask the question again to listen.",
    },
  },
  it: {
    eyebrow: "Una parola discreta, quando serve",
    title: "Il tuo concierge personale",
    lead:
      "Chiedi un tavolo, un bagno al mare o una giornata lenta. Rispondiamo dalla nostra guida di Positano, lasciando a te ogni scelta.",
    languageLabel: "Lingua del concierge",
    voiceLegend: "Voce",
    voices: { female: "Voce femminile", male: "Voce maschile" },
    aiDisclosure: "La voce che ascolti è generata dall’intelligenza artificiale.",
    privacyNote:
      "Quando usi il concierge, la domanda, una breve cronologia e le schede pertinenti della guida vengono inviate a OpenAI. Se scegli Ascolta, il testo della risposta viene inviato di nuovo per generare l’audio. Non inserire dati sensibili o riservati.",
    chatTitle: "Concierge Fenice",
    checking: "Verifica in corso",
    ready: "Disponibile",
    unavailable: "Momentaneamente non disponibile",
    newConversation: "Nuova conversazione",
    confirmNewConversation: "Conferma azzeramento",
    welcome:
      "Benvenuti. Raccontami che momento avete in mente e vi aiuterò a orientarvi tra i nostri indirizzi di Positano.",
    assistantName: "Concierge",
    guestName: "Tu",
    quickPrompts: [
      "Una cena in famiglia qui vicino",
      "Una giornata tranquilla al mare",
      "Cosa possiamo vedere oggi?",
      "Come possiamo muoverci?",
    ],
    suggestionsLabel: "Suggerimenti",
    inputLabel: "Chiedi al concierge",
    inputPlaceholder: "Per esempio: dove possiamo cenare con calma?",
    send: "Invia",
    sending: "Ci penso…",
    listen: "Ascolta",
    stop: "Interrompi",
    officialSite: "Sito ufficiale",
    maps: "Maps",
    request: "Chiedi a La Fenice",
    errors: {
      invalid_request: "Accorcia o riformula la domanda.",
      invalid_origin: "La richiesta non può essere inviata da questa pagina.",
      not_authenticated: "Accedi di nuovo per usare il concierge virtuale.",
      not_configured: "Il concierge virtuale non è ancora stato collegato.",
      rate_limited: "Facciamo una breve pausa. Riprova tra poco.",
      content_blocked: "Non posso aiutarti con questa richiesta. Prova con una domanda sul soggiorno.",
      provider_unavailable: "Il concierge riposa un momento. La guida qui sotto resta disponibile.",
      invalid_speech_token: "Questo ascolto è scaduto. Ripeti la domanda per generarlo di nuovo.",
    },
  },
  de: {
    eyebrow: "Ein diskreter Rat, wenn Sie ihn brauchen",
    title: "Ihr persönlicher Concierge",
    lead:
      "Fragen Sie nach einem Tisch, einem Bad im Meer oder einem ruhigen Tag. Wir antworten anhand unseres Positano-Guides; die Wahl bleibt ganz bei Ihnen.",
    languageLabel: "Sprache des Concierge",
    voiceLegend: "Stimme",
    voices: { female: "Weibliche Stimme", male: "Männliche Stimme" },
    aiDisclosure: "Die Stimme, die Sie hören, wird von künstlicher Intelligenz erzeugt.",
    privacyNote:
      "Wenn Sie den Concierge nutzen, werden Ihre Frage, ein kurzer Gesprächsverlauf und die passenden Guide-Einträge an OpenAI gesendet. Wenn Sie Anhören wählen, wird der Antworttext erneut zur Audioerzeugung gesendet. Geben Sie keine sensiblen oder vertraulichen Daten ein.",
    chatTitle: "Fenice Concierge",
    checking: "Verfügbarkeit wird geprüft",
    ready: "Verfügbar",
    unavailable: "Vorübergehend nicht verfügbar",
    newConversation: "Neues Gespräch",
    confirmNewConversation: "Zurücksetzen bestätigen",
    welcome:
      "Willkommen. Erzählen Sie mir, wonach Ihnen ist, und ich helfe Ihnen bei der Auswahl unserer Adressen in Positano.",
    assistantName: "Concierge",
    guestName: "Sie",
    quickPrompts: [
      "Ein Familienessen in der Nähe",
      "Ein ruhiger Tag am Meer",
      "Was können wir heute sehen?",
      "Wie bewegen wir uns am besten fort?",
    ],
    suggestionsLabel: "Vorschläge",
    inputLabel: "Den Concierge fragen",
    inputPlaceholder: "Zum Beispiel: Wo können wir in Ruhe zu Abend essen?",
    send: "Senden",
    sending: "Ich überlege…",
    listen: "Anhören",
    stop: "Stoppen",
    officialSite: "Offizielle Website",
    maps: "Maps",
    request: "La Fenice fragen",
    errors: {
      invalid_request: "Bitte kürzen oder formulieren Sie Ihre Frage neu.",
      invalid_origin: "Die Anfrage kann von dieser Seite nicht gesendet werden.",
      not_authenticated: "Bitte melden Sie sich erneut an, um den Concierge zu nutzen.",
      not_configured: "Der virtuelle Concierge ist noch nicht verbunden.",
      rate_limited: "Bitte eine kurze Pause. Versuchen Sie es gleich noch einmal.",
      content_blocked: "Dabei kann ich nicht helfen. Stellen Sie bitte eine Frage zu Ihrem Aufenthalt.",
      provider_unavailable: "Der Concierge macht kurz Pause. Der Guide darunter bleibt verfügbar.",
      invalid_speech_token: "Dieser Audiolink ist abgelaufen. Stellen Sie die Frage erneut.",
    },
  },
  ru: {
    eyebrow: "Ненавязчивый совет, когда он нужен",
    title: "Ваш личный консьерж",
    lead:
      "Спросите о столике, купании или неспешном дне. Мы отвечаем по нашему путеводителю по Позитано, оставляя выбор за вами.",
    languageLabel: "Язык консьержа",
    voiceLegend: "Голос",
    voices: { female: "Женский голос", male: "Мужской голос" },
    aiDisclosure: "Голос, который вы слышите, создан искусственным интеллектом.",
    privacyNote:
      "При использовании консьержа в OpenAI отправляются ваш вопрос, краткая история диалога и подходящие карточки путеводителя. Если вы выбираете «Слушать», текст ответа отправляется повторно для создания аудио. Не указывайте чувствительные или конфиденциальные данные.",
    chatTitle: "Консьерж Fenice",
    checking: "Проверяем доступность",
    ready: "Доступен",
    unavailable: "Временно недоступен",
    newConversation: "Новый диалог",
    confirmNewConversation: "Подтвердить сброс",
    welcome:
      "Добро пожаловать. Расскажите, какой день вы задумали, и я помогу выбрать места из нашего путеводителя по Позитано.",
    assistantName: "Консьерж",
    guestName: "Вы",
    quickPrompts: [
      "Семейный ужин неподалёку",
      "Спокойный день у моря",
      "Что посмотреть сегодня?",
      "Как удобнее передвигаться?",
    ],
    suggestionsLabel: "Предложения",
    inputLabel: "Спросить консьержа",
    inputPlaceholder: "Например: где можно спокойно поужинать?",
    send: "Отправить",
    sending: "Думаю…",
    listen: "Слушать",
    stop: "Остановить",
    officialSite: "Официальный сайт",
    maps: "Maps",
    request: "Спросить La Fenice",
    errors: {
      invalid_request: "Сократите или переформулируйте вопрос.",
      invalid_origin: "Запрос нельзя отправить с этой страницы.",
      not_authenticated: "Войдите снова, чтобы пользоваться консьержем.",
      not_configured: "Виртуальный консьерж пока не подключён.",
      rate_limited: "Нужна небольшая пауза. Попробуйте ещё раз чуть позже.",
      content_blocked: "Я не могу помочь с этим запросом. Задайте вопрос о вашем проживании.",
      provider_unavailable: "Консьерж ненадолго отошёл. Путеводитель ниже остаётся доступен.",
      invalid_speech_token: "Срок действия аудио истёк. Задайте вопрос ещё раз.",
    },
  },
};
